<?php

namespace AppBundle\Repository;

/**
 * KomisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomisRepository extends \Doctrine\ORM\EntityRepository
{
}
