app:
    resource: '@AppBundle/Controller/'
    type: annotation

cars_index:
  path: /
  defaults: {_controller: AppBundle:Cars:index}

cars_cars:
  path: /cars
  defaults: {_controller: AppBundle:Cars:cars}

cars_add:
  path: /cars/add
  defaults: {_controller: AppBundle:Cars:add}


