app:
    resource: '@AppBundle/Controller/'
    type: annotation

car_index:
  path: /
  defaults: {_controller: AppBundle:Car:index}

car_cars:
  path: /cars
  defaults: {_controller: AppBundle:Car:cars}

car_add:
  path: /cars/add
  defaults: {_controller: AppBundle:Car:add}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


